name: Bot Morpho Stake DAO

on:
  workflow_dispatch:
    inputs:
      dispatch_id:
        type: string
        description: "Unique ID for Temporal tracking"
        required: false
        default: ""

jobs:
  run:
    uses: ./.github/workflows/_bot.yml
    secrets: inherit
    with:
      dispatch_id: ${{ inputs.dispatch_id }}
      scripts: script/bots/morpho/main.py
